spring:
  session:
    store-type: redis
  redis:
    port: 6379
zuul: 
  retryable: true
  routes:
    order-management-ms:
      path: /order-management-ms/**
      sensitiveHeaders: Authorization, Set-Cookie
security:
  user:
    name: gateway
    password: password

